### ISSUE TITLE
Upgrading the dependencies

### ISSUE THREAD

**Issue by mdenti** [rquadling/grunt-html2js#101]
Hello,

the dependencies for the package are our of date, `npm audit` gives this result:
> found 75 vulnerabilities (9 moderate, 64 high, 2 critical) in 3666 scanned packages

if possible, could we get a new version with updated (and secure) dependencies?

thanks!

**Comment by rquadling** [comment]
Just released 0.7.0
Upgraded dependencies to latest versions.`npm audit` shows 0 vulnerabilities.
