### ISSUE TITLE
New release to include removal of `istanbul` as dependency

### ISSUE THREAD

**Issue by mbzzt** [rquadling/grunt-html2js#116]
Hey guys,
May I ask you, please, to do a new release with the latest security updates?
I noticed there are many commits in master that were not yet included in any release.
The one I am more interested in, is the removal of `istambul` as dependency. Using `grunt-html2js` latest version released, `0.8.0`, it makes our apps to have security vulnerabilities reports, because it still includes `"istanbul": "^0.4.5"` as dependency, which has many outdated and vulnerabilities dependencies.
If I can help in any way, please let me know.
Thanks in advance!

**Comment by runderworld** [comment]
@mbzzt  :   @rquadling merged PR #110 last year, which achieves your request. The only problem is that he didn't build a new release, so it's just sitting on master. If you (or others reading this) want to take advantage of it, you can do:

```
"grunt-html2js": "rquadling/grunt-html2js#master",
```

**Comment by rquadling** [comment]
Hi. Sorry for the very very significant delay.

**Comment by rquadling** [comment]
https://www.npmjs.com/package/grunt-html2js
