### ISSUE TITLE
Extracting logic to standalone node module

### ISSUE THREAD

**Issue by PascalPrecht** [rquadling/grunt-html2js#23]
Hey @karlgoldstein !

A few days ago I thought it could be a good thing to extract the main logic out of grunt-html2js and publish it as a standalone node module. The grunt task would rather be a wrapper to work with grunt.

Why? Because we now also have the gulp task runner and it could be a cool thing to have html2js in that env too :) wdyt?

**Comment by rquadling** [comment]
Looking to close this issue. I have no experience with gulp. If you can present a PR, then I'd gladly look into it.

**Comment by rquadling** [comment]
Closing.
