### ISSUE TITLE
If template is empty, don't produce a module?

### ISSUE THREAD

**Issue by mdedetrich** [rquadling/grunt-html2js#34]
As is commonly done in `jade`, I typically have my mixins put in a subfolder, which just contain mixins, these mixins then get mixed in by the parent folder. An example mixin is something like this

``` jade
mixin awesomeMixin
    #someId.thisIsAnAwesomeMixin
```

Assuming a `.jade` file will only contain the above (i.e. only mixins), the resulting template will be an empty string.

Long story short, should there be an option where if a resulting template is empty (i.e. `jade` file only contains `mixin`s), then `grunt-html2js` wont create an angularModule for that `.jade` file at all?

**Comment by rquadling** [comment]
I suppose the difficulty would be differentiating between a genuine empty module and one that Pug (the replacement for Jade) has created that is empty that was only mixins.

The template doesn't really advertise its intent, so they all get treated equally.

Would it be appropriate to have an option that suppressed empty Pug templates - empty from the perspective of the results of the Pug compile process?

If so, then a new option for grunt-html2js could be added to suppress these empty compiled templates.

I don't think it would be right to suppress all empty modules (i.e. ones that are NOT Pug templates) as, like I said, there's no way to determine the intent of the template.

**Comment by rquadling** [comment]
I relatively recently became owner of this project, so please forgive any tardiness in the reply.

**Comment by rquadling** [comment]
Suppression of empty modules was implemented in v0.4.2
