### ISSUE TITLE
Support node-glob / minimatch style base option

### ISSUE THREAD

**Issue by rehno-lindeque** [rquadling/grunt-html2js#4]
It would be quite useful to support something like [node-glob](https://github.com/isaacs/node-glob)  / [minimatch](https://github.com/isaacs/minimatch) style expansion for the `base` option similar to http://gruntjs.com/configuring-tasks#globbing-patterns

E.g. The following would create a cache reference to `"slider-template.html"` instead of `"angular-slider/slider-template.html"`...

``` coffee
    html2js:
      vendor:
        options: base: "components/**/"
        files:
          ".tmp/templates/vendor.js": [ "components/angular-slider/slider-template.html"]
```

...which is how the template is being loaded in the [angular-slider](https://github.com/prajwalkman/angular-slider/blob/master/angular-slider.js#L103) library, for example.

**Comment by karolmajta** [comment]
+1 for this one.

Maybe instead of using a glob pattern a better approach would be to allow to specify a function
that takes the original function and returns module name that would transform the original file path to
module name?

**Comment by rquadling** [comment]
Is this still an issue?

**Comment by rquadling** [comment]
Closing.
