### ISSUE TITLE
Mix of single and double quotes

### ISSUE THREAD

**Issue by adampoczatek** [rquadling/grunt-html2js#44]
`quoteChar` works only inside the module. Module is using single quotes no matter what settings you have.

Example:

`quoteChar: '\''`:

```
angular.module('moduleName.Templates', []).run(['$templateCache', function($templateCache) {
    $templateCache.put('templates/example.html',
        '<h1>Heey</h1>');
    $templateCache.put('templates/example2.html',
        '<h1>Heey 2</h1>');
}]);
```

and `quoteChar: '"'`:

```
angular.module('moduleName.Templates', []).run(['$templateCache', function($templateCache) {
    $templateCache.put("templates/example.html",
        "<h1>Heey</h1>");
    $templateCache.put("templates/example2.html",
        "<h1>Heey 2</h1>");
}]);
```

Also, any chance you could add option to wrap everything with IIFE? I know you can use `fileHeaderString` / `fileFooterString` but it won't indent the contents.

**Comment by brunowego** [comment]
About the IIFE, I use [grunt-iife](https://www.npmjs.com/package/grunt-iife) to wrap grunt-html2js.
