### ISSUE TITLE
support for wrapping output in AMD module

### ISSUE THREAD

**Issue by anwalkers** [rquadling/grunt-html2js#56]
Would be great if there was an configuration option for output wrapped in a AMD pattern. Maybe it is already there...

<pre><code>(function (define, angular) {
    'use strict';
    define([], function () {
        var moduleName = 'templates/helloworld.tpl.html';

        angular.module(moduleName, []).run(['$templateCache', function($templateCache) {
            $templateCache.put('moduleName',
            '&lt;div>TEMPLATE MARKUP&lt;/div>');
        }]);

        return moduleName;
    });
})(define, angular);
</code></pre>

**Comment by mpint** [comment]
Agreed here.  It's difficult to use this tool using RequireJS to add modules to a parent project without mudding up the requireConfig file.  

Angular is not defined in the myHtml2jsTemplates.js, which requires you to manually shim each template module you define, unless I'm missing something.

**Comment by mpint** [comment]
I found somewhat of a fix.

Here's my abbreviated code.

requireConfig
```    
    shim: {
        'test': ['angular']
    },
packages: [
        {
            name: 'test',
            main: '_index.es6',
            location: './src'
        }
    ]
```
angular module
```
import '../test.html2jstemplates';
export default angular.module('test', ['test.html2jstemplates']);
```

**Comment by rquadling** [comment]
AMD support seems to be implemented.
