### ISSUE TITLE
htmlmin, collapseWhitespace and bootstrap-ui's form-inline

### ISSUE THREAD

**Issue by germanger** [rquadling/grunt-html2js#62]
Maybe I should ask this directly on the htmlmin github page, but I'm not sure.

I noticed that this configuration:

```
            htmlmin: {
                collapseWhitespace: true,
                removeComments: true,
                collapseBooleanAttributes: false,
                removeAttributeQuotes: false,                   
                removeEmptyAttributes: false,
                removeRedundantAttributes: false,
                removeScriptTypeAttributes: false,
                removeStyleLinkTypeAttributes: false
            }
```

And this piece of html (bootstrap-ui)

```
<form class="form-inline">
    <div class="form-group">
        <button class="btn btn-default btn-sm"><span class="glyphicon glyphicon-pencil"></span></button>
    </div>
    <div class="form-group">
        <button class="btn btn-default btn-sm"><span class="glyphicon glyphicon-repeat" /></button>
    </div>
    <div class="form-group">
        <button class="btn btn-default btn-sm" ><span class="glyphicon glyphicon-remove" /></button>
    </div>
</form>
```

Results in this:
![image](https://cloud.githubusercontent.com/assets/2080549/6044987/a1b98814-ac75-11e4-8e1f-bfa57d51aea3.png)

And when I turn off "collapse white space", ie:

```
  collapseWhitespace: false,
```

I get the correct display
![image](https://cloud.githubusercontent.com/assets/2080549/6044967/8b95ebf4-ac75-11e4-91e1-3932e283a511.png)

So...
1. Should I ask this in htmlmin?
2. How can I solve this?

**Comment by softsimon** [comment]
I just got the same issue enabling collapseWhitespace and I found the solution:
Add: conservativeCollapse: true,   this will always leave atleast one space between elements instead of removing them completely. So set both these to true.

collapseWhitespace: true,
conservativeCollapse: true,

**Comment by germanger** [comment]
Awesome! I will try it and come back with feedback.

**Comment by germanger** [comment]
It worked, but is weird because looking at the output js, I'm seeing things like this:

    <div class="ngCellText" ng-class="col.colIndex()">\n            {{row.entity.weight - row.entity.processed - row.entity.dispatched | number: 2}}\n        </div></script> <div ....etc

Is that a normal output when using this two options? there's a \n and also more than "atleast one space" (i'm seeing like 12)

**Comment by rquadling** [comment]
Is this still an issue?

**Comment by rquadling** [comment]
No feedback. A workaround was provided. Closing.
