### ISSUE TITLE
If the template isn't found, then it should throw an error.

### ISSUE THREAD

**Issue by vandermore** [rquadling/grunt-html2js#76]
If in the src attribute array, the full path to a file is given, and that file doesn't exist, right now it just continues without any errors or warnings.

It should throw an error if a specific file isn't found.

**Comment by rquadling** [comment]
Happy to look at a pull request for this.

**Comment by rquadling** [comment]
If the grunt setting of `nonull: true` is used, then you get a warning produced by grunt-html2js, but this doesn't stop the build process.

https://github.com/gruntjs/grunt-contrib-concat/issues/57

**Comment by rquadling** [comment]
Closing.
