### ISSUE TITLE
Template with broken newlines generates broken javascript

### ISSUE THREAD

**Issue by nothrow** [rquadling/grunt-html2js#79]
When you have template that contains Mac-style (\r) newlines, it generates broken javascript. I've seen it with misconfigured git.

When there are alone \r's, they are mistakenly converted to newline and not escaped.
Example (with newline chars visible):

```
abc\r\r\n
def
```

creates

```
"abc
\n" + 
"def" 
```

**Comment by rquadling** [comment]
This should now be fixed in 0.3.8
