### ISSUE TITLE
Parse error on < (less than) symbol in Angular expression

### ISSUE THREAD

**Issue by skylarmb** [rquadling/grunt-html2js#96]
Using the default htmlmin options from the example: 

```
htmlmin: {
  collapseBooleanAttributes: true,
  collapseWhitespace: true,
  removeAttributeQuotes: true,
  removeComments: true,
  removeEmptyAttributes: true,
  removeRedundantAttributes: true,
  removeScriptTypeAttributes: true,
  removeStyleLinkTypeAttributes: true
}
```

and using this or any similar expression in a template. 

`{{foo.length < 5 ? 'bar' : 'baz'}}`

I get `Error: Parse Error: <`

Disabling individual htmlmin attributes doesn't seem to help

**Comment by rquadling** [comment]
Can you show me an example template?

I'm my app, we only have `'<'` inside attributes, not in a template.

For example:

`ng-show="orderItem.qty > 0 && orderItem.redeemed < orderItem.qty"`

**Comment by skylarmb** [comment]
Sure. 

```
<p> Is the number 4 less than the number 5? {{ 4 < 5 ? 'Yes' : 'No' }} </p>
```

This errors out. 

A temporary workaround is reversing the ternary to be 

```
<p> Is the number 4 less than the number 5? {{ 5 > 4 ? 'Yes' : 'No' }} </p>
```

This works fine, but I feel like the `<` operator should not cause an error. This could cause many issues when adding `html2js` to an existing application

**Comment by rquadling** [comment]
> ignoreCustomFragments
> Array of regex'es that allow to ignore certain fragments, when matched (e.g. `<?php ... ?>`, `{{ ... }}`, etc.)
> `[ /<%[\s\S]*?%>/, /<\?[\s\S]*?\?>/ ]`

Set this option.
```
                    ignoreCustomFragments: [
                        /<%[\s\S]*?%>/,
                        /<\?[\s\S]*?\?>/,
                        /{{[\s\S]*?}}/
                    ],
```

**Comment by rquadling** [comment]
This is the output from one of my templates:

`<p>Is the number 4 less than the number 5? {{ 4 < 5 ? 'Yes' : 'No' }} </p><p>Is the number 4 less than the number 5? {{ 5 > 4 ? 'Yes' : 'No' }} </p>`

Without the option, I get the same error as you had.

Thank you for reporting this.
